// <auto-generated />
using AgenciaAirVibes_MetodosAssincronos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciaAirVibes_MetodosAssincronos.Migrations
{
    [DbContext(typeof(_DbContext))]
    partial class _DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AgenciaAirVibes_MetodosAssincronos.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DataIda")
                        .HasColumnType("longtext");

                    b.Property<string>("DataVolta")
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext");

                    b.Property<string>("NomePas")
                        .HasColumnType("longtext");

                    b.Property<string>("Partida")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("passagem");
                });
#pragma warning restore 612, 618
        }
    }
}
